import fs from "fs-extra";
import path from "path";
import type { GeoDataConfig } from "./config.js";
import { getInstalledCountries } from "./helpers.js";

export async function generateIndex(config: GeoDataConfig): Promise<void> {
  const codes = await getInstalledCountries(config.outputDir);

  const validCodePattern = /^[a-z]{2}$/;
  const safeCodes = codes.filter((code) => {
    if (!validCodePattern.test(code)) {
      console.warn(`Skipping invalid country code: ${code}`);
      return false;
    }
    return true;
  });

  const ext = config.typescript ? "ts" : "js";
  const indexPath = path.join(config.outputDir, `index.${ext}`);

  // Handle empty case
  if (safeCodes.length === 0) {
    const emptyContent = config.typescript
      ? `// Auto-generated by geo-data - no countries installed yet
// Run: npx geo-data add <country>

export const countries = {} as const;
export type CountryCode = never;
`
      : `// Auto-generated by geo-data - no countries installed yet
// Run: npx geo-data add <country>

export const countries = {};
`;
    await fs.writeFile(indexPath, emptyContent);
    return;
  }

  // Sort codes for consistent output
  safeCodes.sort();

  const imports = safeCodes.map((code) => `import ${code}Data from './${code}.json' with { type: "json" };`).join("\n");

  const countriesObj = safeCodes.map((code) => `  ${code.toUpperCase()}: ${code}Data,`).join("\n");

  const types = config.typescript
    ? `
export type CountryCode = keyof typeof countries;
export type Country = (typeof countries)[CountryCode];
export type Region = Country['regions'][number];
export type City = Region['cities'][number];
export type LocalizedName = { name: { [key: string]: string | undefined; en: string } };
`
    : "";

  const content = `// Auto-generated by geo-data - do not edit manually
// Regenerate with: npx geo-data update
${imports}

export const countries = {
${countriesObj}
} as const;
${types}
export function getCountry${config.typescript ? "(code: CountryCode)" : "(code)"} {
  return countries[code];
}

export function getRegions${config.typescript ? "(code: CountryCode)" : "(code)"} {
  return countries[code].regions;
}

export function getCities${config.typescript ? "(code: CountryCode, regionCode?: string)" : "(code, regionCode)"} {
  const regions = getRegions(code);
  if (regionCode) {
    const region = regions.find(r => r.code === regionCode);
    return region?.cities ?? [];
  }
  return regions.flatMap(r => r.cities);
}

export function getAllCities${config.typescript ? "(code: CountryCode)" : "(code)"} {
  return getRegions(code).flatMap(r => r.cities);
}

export function getLocalizedName${config.typescript ? '(item: { name: Record<string, string | undefined> & { en: string } }, lang: string = "en"): string' : '(item, lang = "en")'} {
  return item.name[lang] ?? item.name.en;
}

export function getCountryCodes()${config.typescript ? ": CountryCode[]" : ""} {
  return Object.keys(countries)${config.typescript ? " as CountryCode[]" : ""};
}

export function isValidCountryCode${config.typescript ? "(code: string): code is CountryCode" : "(code)"} {
  return code in countries;
}
`;

  await fs.writeFile(indexPath, content.trim() + "\n");
}
